/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package camaras.view;

import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Taskbar;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author luis
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final String urlVideo1 = "rtsp://192.168.100.150:554/user=admin&password=&channel=1&stream=1.sdp?real_stream--rtp-caching=100";
    private final String urlVideo2 = "rtsp://192.168.100.150:554/user=admin&password=&channel=2&stream=1.sdp?real_stream--rtp-caching=100";
    private final String urlVideo3 = "rtsp://192.168.100.150:554/user=admin&password=&channel=3&stream=1.sdp?real_stream--rtp-caching=100";
    private final String urlVideo4 = "rtsp://192.168.100.150:554/user=admin&password=&channel=4&stream=1.sdp?real_stream--rtp-caching=100";
    private final Taskbar taskbar;
    private final Image iconoApp;
    
    /**
     * Creates new form Principal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Camaras");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        iconoApp = new ImageIcon(getClass().getResource("/img/camara.png")).getImage();
        setIconImage(iconoApp);
        taskbar = Taskbar.getTaskbar();
        taskbar.setIconImage(iconoApp);
        add(new Camara("Camara 1",urlVideo1));
        add(new Camara("Camara 2",urlVideo2));
        add(new Camara("Camara 3",urlVideo3));
        add(new Camara("Camara 4",urlVideo4));
        //pack();
        setLocationRelativeTo(null);
        setVisible(true);
        systemTray(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));
    }// </editor-fold>//GEN-END:initComponents

    
    private void systemTray(JFrame ventana){
        if (!SystemTray.isSupported()) {
            System.out.println("SystemTray is not supported");
            return;
        }
        final PopupMenu popup = new PopupMenu();
        final TrayIcon trayIcon = new TrayIcon(createImage("../../img/camara.png", "camaras"));
        final SystemTray tray = SystemTray.getSystemTray();
        
        
        MenuItem abrirItem = new MenuItem("Abrir");
        MenuItem salirItem = new MenuItem("Salir");
        popup.add(abrirItem);
        popup.add(salirItem);
        
        abrirItem.addActionListener((ActionEvent e) -> {
            ventana.setVisible(true);
        });
        
        salirItem.addActionListener(((e) -> {
            tray.remove(trayIcon);
            System.exit(0);
        }));
        
        trayIcon.setPopupMenu(popup);
        
    }
    
    protected Image createImage(String path, String description) {
        
        URL imageURL = VentanaPrincipal.class.getResource(path);
        
        if (imageURL == null) {
            System.err.println("Resource not found: " + path);
            return null;
        } else {
            return (new ImageIcon(imageURL, description)).getImage();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
